# Site settings
title: 浅唱博客
SEOTitle: 浅唱博客
header-img: img/post-bg-desk.jpg
email: qcnhy@qq.com
description: "在这里与你分享生活"
keyword: "浅唱博客, 1029374115, qcnhy, 浅唱, 浅唱那回忆"
url: "https://blog.qcnhy.cn"       # your host, for absolute URL
enforce_ssl: blog.qcnhy.cn
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/qcnhy/qcnhy.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "在这里与你分享生活"
sidebar-avatar: /img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: true
# weibo_username:     qiubaiying
# zhihu_username:     qiubaiying
github_username:    qcnhy
# facebook_username:  baiying.qiu.7
# jianshu_username:   e71990ada2fd
# twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins:
#  - jekyll-sitemap
  - jekyll-paginate




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 1efeaf1a76e238f70f6e                            #生成的clientID
  clientSecret: 7a477b20ac33f82201c3094d60139cdcd1979228    #生成的clientSecret
  repo: qcnhy.github.io    #仓库名称
  owner: qcnhy    #github用户名
  admin: qcnhy     
  distractionFreeMode: true #是否启用类似FB的阴影遮罩
  createIssueManually: true #打开页面自动初始化


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 03c3c465b1dd8f67c7e360bcb37bd29b

# Google Analytics
ga_track_id: 'UA-145388892-1'            # Format: UA-xxxxxx-xx
ga_domain: blog.qcnhy.cn             # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "浅唱云任务",
        href: "http://mz.qcnhy.cn"
    },{
        title: "浅唱发卡网",
        href: "https://fk.qcnhy.cn"
    },{
        title: "漳三吐槽墙",
        href: "http://tc.qcnhy.cn/"
    }
]
